config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users
  resources :movies
  resources :directors
  resources :lists
  resources :genres
  resources :actors

  # search and result from the TMDB using API
  get '/tmdb_result'=> 'pages#tmdb_result', :as => 'tmdb_result'
  get '/movies/add/:id' => 'movies#add', :as => 'add_movie'

  # session routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # search and result routes
  get '/show' => 'pages#search', :as => 'search'
  get '/result' => 'pages#result', :as => 'result'

  # route to user's lists
  get '/my_lists' => 'pages#my_lists', :as => 'my_lists'
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_and_belongs_to_many :movies
  has_and_belongs_to_many :lists
  has_many :directors, :through => :movies
  has_many :genres, :through => :movies

  # validates :imdb_id, :uniqueness => true
  validates :tmdb_id, :uniqueness => true

  # start of PgSearch set up
  include PgSearch::Model
  pg_search_scope :search, against: :name,
    associated_against: {
      genres: :name,
      directors: :name,
      movies: :title
    },
    :using => {
      :tsearch => {
        :dictionary => "english",
        :prefix => true
      },
      :trigram => {
        :word_similarity => true,
        :threshold => 0.3
      }
    }

    def self.text_search query
      if query.present?
        search(query)
      else
        scoped
      end
    end
   # end of PgSearch

end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  has_secure_password

  has_many :reviews
  has_many :movies, :through => :reviews

  validates :email, :presence => true, :uniqueness => { :case_sensitive => false }, :length => { :minimum => 5 }
  validates :username, :presence => true, :uniqueness => { :case_sensitive => false }, :format => { with: /\A[a-zA-Z0-9]+\Z/ }
  validates :password, :presence => true, :length => { :minimum => 5, :maximum => 20 }
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :check_for_admin, :only => [:destroy]
  before_action :check_for_login, :only => [:add, :create, :edit, :update]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    movie = Movie.create movie_params
    redirect_to movie
  end

  def add
    tmdb_id = params[:id]
    if Movie.find_by(:tmdb_id => tmdb_id).present?
      @movie = Movie.find_by :tmdb_id => tmdb_id
    else
      @movie = Movie.create_movie_from_tmdb tmdb_id
    end
    redirect_to movie_path(@movie.id)
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    movie = Movie.find params[:id]
    movie.update movie_params
    redirect_to movie
  end

  def show
    @movie = Movie.find params[:id]
    id = params[:id]
    if @current_user.present?
      movie_lists = @current_user.lists.where(:category => 'Movies')
      @lists_movie_is_in  = []
      movie_lists.each do |list|
        list.movies.each do |film|
          if film[:id] == @movie.id
            @lists_movie_is_in << list
          end
        end
      end
    end
    youtube_url = @movie.youtube
    youtube_id = Movie.get_youtube_id youtube_url
    @embed_url = "https://youtube.com/embed/" + youtube_id
    if @movie.duration.present?
      duration = @movie.duration
      @duration = Movie.convert_duration duration
    end
    @top_five_actors = @movie.actors[0..4]

  end

  private
  def movie_params
    params.require(:movie).permit(:title, :year, :overview, :classification, :duration, :image, :imdb_id, :tmdb_id, :director_id, :youtube, :genre_ids => [],:list_ids => [])
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
<div class="col-lg-4 actor-form">
  <div class="form-group top-buffer">
    <div class="input-tag">
      <%= f.label :title %>
    </div>
    <div class="input-field">
      <%= f.text_field :title, :required => true, :autofocus => true, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :year %>
    </div>
    <div class="input-field">
      <%= f.number_field :year, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :overview %>
    </div>
    <div class="input-field">
      <%= f.text_field :overview, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-field">
      <%= f.label :duration %>
    </div>
    <div class="input-tag">
      <%= f.number_field :duration, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :image %>
    </div>
    <div class="input-field">
      <%= f.url_field :image, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :imdb_id, "IMDB id" %>
    </div>
    <div class="input-field">
      <%= f.text_field :imdb_id, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :tmdb_id, "TMDB id" %>
    </div>
    <div class="input-field">
      <%= f.number_field :tmdb_id, :class => 'form-control' %>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="input-tag">
    <%= f.label :director_id, "Director" %>
  </div>
  <div class="input-field">
    <%= f.select :director_id, Director.pluck(:name, :id).sort, :include_blank => true, :class => 'form-control-lg' %>
  </div>
</div>
  <div class="input-tag">
    <%= f.label :genre_ids, "Genres" %>
  </div>
    <div class="form-check">
      <%= hidden_field_tag "movie[genre_ids][]", nil %>
      <% Genre.all.order('name').each do |genre| %>
        <%= check_box_tag "movie[genre_ids][]", genre.id, @movie.genre_ids.include?(genre.id), id: dom_id(genre) %>
        <%= label_tag dom_id(genre), genre.name %><br>
      <% end %>
    </div>
  <div class="submit-button">
    <%= f.submit "Submit", :class=> "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/movies/_modal.html.erb
<% if @current_user.present? %>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-movie-modal">
  Update lists
  </button>
<% end %>

<%= form_for @movie do |f| %>
<div class="modal fade" id="add-movie-modal" tabindex="-1" role="dialog" aria-labelledby="add-movie-modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="add-movie-modal">Add movie to selected lists:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <% if @current_user.present? %>
            <%= hidden_field_tag "movie[list_ids][]", nil %>
            <% @current_user.lists.where(:category => 'Movies').all.each do |list| %>
              <%= check_box_tag "movie[list_ids][]", list.id, @movie.list_ids.include?(list.id), id: dom_id(list) %>
              <%= label_tag dom_id(list), list.name %><br>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Save", :class => 'btn btn-secondary', :id => 'save-btn-movie' %>
            <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<h1>Movies</h1>
<div class="container">
  <form class="search-movies" action="/tmdb_result" method="get">
    <div class="tmdb-search row">
      <div class="col-3">
        <input type="search" name="title" required placeholder="Find on TMDB" class="form-control">
      </div>
      <div class="col-1">
        <button class="btn btn-outline-primary">Search</button>
      </div>
    </div>
  </form>
</div>

<div class="board minor-top-buffer">
  <% @movies.each do |movie| %>
  <div class="tile">
    <div class="photo">
      <%= link_to image_tag(movie.image, :class => 'thumb', :alt => movie.title), movie if movie.image.present? %>
    </div>
   </div>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1>Add movie</h1>

<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<div class="movie-show-page">
  <section class="movie-title-block">
    <h1><%= @movie.title %></h1>
    <% if @current_user.present? && @current_user.admin? %>
      <%= link_to "Edit", edit_movie_path(@movie) %>
      <%= link_to "Delete", @movie, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
    <% end %>
    <p id="movie-minor-info">
      <span><%= @movie.classification if @movie.classification.present? %></span>
      <span><%= @duration if @duration.present? %></span>
      <% @movie.genres.each do |genre| %>
        <span><%= link_to genre.name, genre %></span>
      <% end %>
    </p>
  </section>

  <div class="container movie-profile">
    <div class="row justify-content-between">
      <div class="hero-poster col-12 col-md-4">
        <%= image_tag @movie.image, :class => 'feature', :alt => @movie.title if @movie.image.present? %>
      </div>
      <div class="trailer col-12 col-md-8">
        <iframe width="100%" height="450" src=<%= @embed_url %> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>

  <div class="container movie-info">
    <div class='row top-buffer'>
      <div id="overview" class="col-12 col-md-8">
        <h3>Overview</h3>
        <p id="plot" align="justify"><%= @movie.overview %></p>
        <h3>Director</h3>
        <h4><%= link_to @movie.director.name, @movie.director %></h4>
      </div>
      <div class="list col-12 col-md-4">
        <% if @current_user.present? %>
          <h3>Lists this movie is in:</h3>
          <% if @lists_movie_is_in.count == 0 %>
            <p>None</p>
          <% else %>
          <ul>
            <% @lists_movie_is_in.each do |list| %>
              <li><p><%= list.name %></p></li>
            <% end %>
          <% end %>
          </ul>
          <div id="movie-list-modal">
              <%= render :partial => 'modal' %>
          </div>

        <% else %>
          <%= link_to "Sign in to add movie to list", login_path %>
        <% end %>
      </div>
    </div>
  </div>


<h3 class="minor-top-buffer">Main casts</h3>
<div class="board">
  <% @top_five_actors.each do |actor| %>
  <div class="tile">
    <div class="photo">
      <%= link_to image_tag(actor.image, :class => "thumb", :alt => actor.name), actor %>
    </div>
    <div class="photo-name">
      <h5><%= actor.name %></h5>
    </div>
  </div>
  <% end %>
</div>

<% if @movie.director.movies.count > 1 %>
  <h3 class="minor-top-buffer">Other movies by <%= @movie.director.name %></h3>
    <div class="board">
      <% @movie.director.movies.each do |movie| %>
        <% if movie.image.present? && movie.id != @movie.id %>
        <div class="tile">
          <div class="photo">
            <%= link_to image_tag(movie.image, :class => 'thumb', :alt => movie.title), movie  %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>