config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users
  resources :movies
  resources :directors
  resources :lists
  resources :genres
  resources :actors

  # search and result from the TMDB using API
  get '/tmdb_result'=> 'pages#tmdb_result', :as => 'tmdb_result'
  get '/movies/add/:id' => 'movies#add', :as => 'add_movie'

  # session routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # search and result routes
  get '/show' => 'pages#search', :as => 'search'
  get '/result' => 'pages#result', :as => 'result'

  # route to user's lists
  get '/my_lists' => 'pages#my_lists', :as => 'my_lists'
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies
  has_many :genres, :through => :movies
  has_many :actors, :through => :movies
  has_and_belongs_to_many :lists

  validates :name, :presence => true, :uniqueness => { :case_sensitive => false }
  # validates :imdb_id, :uniqueness => true
  validates :tmdb_id, :uniqueness => true

  # this is part of the PgSearch set up
  include PgSearch::Model
  pg_search_scope :search, against: :name,
    associated_against: {
      genres: :name,
      actors: :name,
      movies: :title
    },
    :using => {
      :tsearch => {
        :dictionary => "english",
        :prefix => true
      },
      :trigram => {
        :word_similarity => true,
        :threshold => 0.3
      }
    }

  def self.text_search query
    if query.present?
      search(query)
    else
      scoped
    end
  end
 # end of PgSearch

end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :check_for_admin, :only => [:destroy]
  before_action :check_for_login, :only => [:new, :edit, :create, :update]

  def index
    @directors = Director.all.sort_by {|key| key["name"]}
  end

  def new
    @director = Director.new
  end

  def create
    director = Director.create director_params
    redirect_to director
  end

  def edit
    @director = Director.find params[:id]
  end

  def update
    director = Director.find params[:id]
    director.update director_params
    redirect_to director
  end

  def show
    @director = Director.find params[:id]
    id = params[:id]
    if @current_user.present?
      if @current_user.lists.where(:category => 'Directors').present?
        director_lists = @current_user.lists.where(:category => 'Directors')
        @lists_director_is_in = []
        director_lists.each do |list|
          list.directors.each do |person|
            if person[:id] == @director.id
              @lists_director_is_in << list
            end
          end
        end
      end
    end
    random_youtube_url = @director.movies.sample.youtube
    youtube_id = Director.get_youtube_id random_youtube_url
    @embed_url = "https://youtube.com/embed/" + youtube_id
  end

  def destroy
    director = Director.find params[:id]
    director.destroy
    redirect_to my_lists_path
  end

  private
  def director_params
    params.require(:director).permit(:name, :dob, :pob, :imdb_id, :tmdb_id, :image, :movie_ids => [],:list_ids => [])
  end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_form.html.erb
<%= form_for @director do |f| %>
<div class="col-lg-4 actor-form">
  <div class="form-group top-buffer">
    <div class="input-tag">
      <%= f.label :name %>
    </div>
    <div class="input-field">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :dob, "Date of birth: " %>
    </div>
    <div class="input-field">
      <%= f.date_field :dob, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :pob, "Place of birth: " %>
    </div>
    <div class="input-field">
      <%= f.text_field :pob, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-tag">
      <%= f.label :image %>
    </div>
    <div class="input-field">
      <%= f.url_field :image, :class => 'form-control' %>
    </div>
  </div>
  <div class="submit-button">
    <%= f.submit "Submit", :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/directors/_modal.html.erb
<% if @current_user.present? %>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-director-modal">
  Update lists
  </button>
<% end %>

<%= form_for @director do |f| -%>
<div class="modal fade" id="add-director-modal" tabindex="-1" role="dialog" aria-labelledby="add-director-modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="add-director-modal">Add director to selected lists:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <% if @current_user.present? %>
            <%= hidden_field_tag "director[list_ids][]", nil %>
            <% @current_user.lists.where(:category => 'Directors').all.each do |list| %>
              <%= check_box_tag "director[list_ids][]", list.id, @director.list_ids.include?(list.id), id: dom_id(list) %>
              <%= label_tag dom_id(list), list.name %><br>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Save", :class => 'btn btn-secondary', :id => 'save-btn-director' %>
            <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/directors/edit.html.erb
<h1>Edit Director</h1>

<%= render :partial => 'form' %>

app/views/directors/index.html.erb
<h1>Directors</h1>

<div class="board">
  <% @directors.each do |director| %>
      <div class="tile">
        <div class="photo">
          <%= link_to image_tag(director.image, :class => 'thumb', :alt => director.name), director if director.image.present? %>
        </div>
        <div class="photo-name">
          <%= link_to director.name, director %>
        </div>
      </div>
  <% end %>
</div>

app/views/directors/new.html.erb
<h1>Add Director</h1>

<%= render :partial => 'form' %>

app/views/directors/show.html.erb
<div class="director-heading">
  <h1><%= @director.name %></h1>
  <% if @current_user.present? && @current_user.admin? %>
    <%= link_to "Edit", edit_director_path(@director)  %>
    <%= link_to "Delete", @director, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
  <% end %>

</div>

<div class="container director-profile">
  <div class="row justify-content-between">
    <div class="hero-poster col-12 col-md-4">
      <%= image_tag @director.image, :class => 'feature', :alt => @director.name if @director.image.present? %>
    </div>
    <div class="trailer col-12 col-md-8">
      <iframe width="100%" height="450" src=<%= @embed_url %> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
  </div>
</div>

<div class="container director-info">
  <div class="row top-buffer">
    <div class="personal-info col-12 col-md-4">
      <% if @director.dob.present? %>
      <p>
        <strong>Date of birth:</strong>
        <%= @director.dob.strftime '%e %B, %Y' %>
      </p>
      <% end %>
      <% if @director.pob.present? %>
      <p>
        <strong>Place of birth:</strong>
        <%= @director.pob %>
      </p>
      <% end %>
    </div>
    <div class="list col-12 col-md-4">
      <% if @current_user.present? %>
        <h3>Lists that this movie is in:</h3>
        <% if @lists_director_is_in.nil? || @lists_director_is_in.empty? %>
          <p>None</p>
        <% else %>
        <ul>
          <% @lists_director_is_in.each do |list| %>
            <li><%= list.name %></li>
          <% end %>
        <% end %>
        </ul>
        <% if @current_user.lists.where(:category => "Directors").present? && @current_user.lists.where(:category => "Directors").count > 0 %>
          <div id="director-list-modal">
          <%= render :partial => 'modal' %>
          </div>
        <% else %>
          <div><%= link_to "Create list", new_list_path %></div>
        <% end %>
        <% else %>
          <%= link_to "Sign in to add director to list", login_path %>
        <% end %>
    </div>
  </div>
</div>

<div class="row top-buffer">
  <div class="col-12">
    <h3>Movies directed by <%= @director.name %></h3>
      <div class="board">
        <% if @director.movies.present? %>
          <% @director.movies.each do |movie| %>
            <div class="tile">
              <div class="photo">
                <%= link_to image_tag(movie.image, :class => 'thumb', :alt => movie.title), movie if movie.image.present? %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>