config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users
  resources :movies
  resources :directors
  resources :lists
  resources :genres
  resources :actors

  # search and result from the TMDB using API
  get '/tmdb_result'=> 'pages#tmdb_result', :as => 'tmdb_result'
  get '/movies/add/:id' => 'movies#add', :as => 'add_movie'

  # session routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # search and result routes
  get '/show' => 'pages#search', :as => 'search'
  get '/result' => 'pages#result', :as => 'result'

  # route to user's lists
  get '/my_lists' => 'pages#my_lists', :as => 'my_lists'
end

app/views/pages/home.html.erb
<h1 class="hero">Discover</h1>

<div class="hero">
  <% @heroes.each do |hero| %>
  <div class="hero-tile">
    <div class="here-photo">
      <%= link_to image_tag(hero.image, :class => 'thumb-hero', :alt => ""), hero if hero.image.present? %>
    </div>
  </div>
  <% end %>
</div>

app/views/pages/my_lists.html.erb
<h1>My Lists</h1>
<h2 class="list-title-main top-buffer">Movies</h2>
<% if @current_user.lists.where(:category => "Movies").present? %>
  <%   @current_user.lists.where(:category => "Movies").each do |list| %>
    <% if list.movies.present? %>
      <div class="list-heading">
        <h3 class="minor-top-buffer">
          <%= link_to list.name, list_path(list), :class => "list-title-secondary" %>
        </h3>
        <span class="add-link">
          <%= link_to "Add", movies_path %>
        </span>
        <span class="edit-link">
          <%= link_to "Edit", edit_list_path(list) %>
        </span>
        <span class="delete-link">
          <%= link_to "Delete", list, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
        </span>
      </div>
      <div class="board">
        <% list.movies.each do |movie| %>
        <div class="tile">
          <div class="photo">
            <%= link_to image_tag(movie.image, :class => 'thumb', :alt => movie.title), movie %>
          </div>
        </div>
        <% end %>
      </div>
    <% else %>
      <h3 class="minor-top-buffer">
        <%= link_to list.name, list_path(list),:class => "list-title-secondary" %>
      </h3>
      <span class="add-link">
        <%= link_to "Add", movies_path %>
      </span>
      <span class="edit-link">
        <%= link_to "Edit", edit_list_path(list) %>
      </span>
      <span class="delete-link">
        <%= link_to "Delete", list, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <p class="no-list">Currently no lists for movies.</p>
<% end %>

<h2 class="list-title-main top-buffer">Actors</h2>
<% if @current_user.lists.where(:category => "Actors").present? %>
  <%   @current_user.lists.where(:category => "Actors").each do |list| %>
    <% if list.actors.present? %>
      <div class="list-heading">
        <h3 class="minor-top-buffer">
          <%= link_to list.name, list_path(list), :class => "list-title-secondary" %>
        </h3>
        <span class="add-link">
          <%= link_to "Add", actors_path %>
        </span>
        <span class="edit-link">
          <%= link_to "Edit", edit_list_path(list) %>
        </span>
        <span class="delete-link">
          <%= link_to "Delete", list, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
        </span>
      </div>
      <div class="board">
        <% list.actors.each do |actor| %>
        <div class="tile">
          <div class="photo">
            <%= link_to image_tag(actor.image, :class => 'thumb', :alt => actor.name), actor %>
          </div>
          <div class="photo-name">
            <%= link_to actor.name, actor %>
          </div>
        </div>
        <% end %>
      </div>
    <% else %>
      <h3 class="minor-top-buffer">
        <%= link_to list.name, list_path(list),:class => "list-title-secondary" %>
      </h3>
      <span class="add-link">
        <%= link_to "Add", actors_path %>
      </span>
      <span class="edit-link">
        <%= link_to "Edit", edit_list_path(list) %>
      </span>
      <span class="delete-link">
        <%= link_to "Delete", list, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <p class="no-list">Currently no lists for actors.</p>
<% end %>

<h2 class="list-title-main top-buffer">Directors</h2>
<% if @current_user.lists.where(:category => "Directors").present? %>
  <%   @current_user.lists.where(:category => "Directors").each do |list| %>
    <% if list.directors.present? %>
      <div class="list-heading">
        <h3 class="minor-top-buffer">
          <%= link_to list.name, list_path(list), :class => "list-title-secondary" %>
        </h3>
        <span class="add-link">
          <%= link_to "Add", directors_path %>
        </span>
        <span class="edit-link">
          <%= link_to "Edit", edit_list_path(list) %>
        </span>
        <span class="delete-link">
          <%= link_to "Delete", list, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
        </span>
      </div>
      <div class="board">
        <% list.directors.each do |director| %>
        <div class="tile">
          <div class="photo">
            <%= link_to image_tag(director.image, :class => 'thumb', :alt => director.name), director %>
          </div>
          <div class="photo-name">
            <%= link_to director.name, director %>
          </div>
        </div>
        <% end %>
      </div>
    <% else %>
      <h3 class="minor-top-buffer">
        <%= link_to list.name, list_path(list),:class => "list-title-secondary" %>
      </h3>
      <span class="add-link">
        <%= link_to "Add", directors_path %>
      </span>
      <span class="edit-link">
        <%= link_to "Edit", edit_list_path(list) %>
      </span>
      <span class="delete-link">
        <%= link_to "Delete", list, :method => 'delete', :data => { :confirm => 'Are you sure?' } %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <p class="no-list">Currently no lists for directors.</p>
<% end %>

app/views/pages/result.html.erb
<h1>Results</h1>
<% if @movies_result.present? %>
<h2 class="minor-top-buffer"><strong>Movies</strong></h2>
<p class="search-number">Found <%= pluralize @movies_result.count, "results" %>.</p>
<div class="board">
  <% @movies_result.each do |movie|%>
    <div class="tile">
      <div class="photo">
        <%= link_to image_tag(movie.image, :class => "thumb", :alt => movie.title), movie if movie.image.present? %>
      </div>
    </div>
  <% end %>
</div>
<% else %>
<p>No movies were found.</p>
<% end %>

<% if @actors_result.present? %>
<h2 class="minor-top-buffer"><strong>Actors</strong></h2>
<p class="search-number">Found <%= pluralize @actors_result.count, "results" %>.</p>
<div class="board">
<% @actors_result.each do |actor|%>
  <div class="tile">
    <div class="photo">
      <%= link_to image_tag(actor.image, :class => "thumb", :alt => actor.name), actor if actor.image.present? %>
    </div>
    <div class="photo-name">
      <%= link_to actor.name, actor_path(actor.id) %>
    </div>
  </div>
  <% end %>
</div>
<% else %>
<p>No actors were found.</p>
<% end %>

<% if @directors_result.present? %>
<h2 class="minor-top-buffer"><strong>Directors</strong></h2>
<p class="search-number">Found <%= pluralize @directors_result.count, "results" %>.</p>
<div class="board">
 <% @directors_result.each do |director|%>
  <div class="tile">
    <div class="photo">
      <%= link_to image_tag(director.image, :class => "thumb", :alt => director.name), director if director.image.present? %>
    </div>
    <div class="photo-name">
      <%= link_to director.name, director %>
      </div>
  </div>
  <% end %>
<% else %>
<p>No directors were found.</p>
<% end %>

app/views/pages/tmdb_result.html.erb
<h2><strong>Results</strong></h2>

<div class="container minor-top-buffer">
  <form class="search-movies" action="/tmdb_result" method="get">
    <div class="tmdb-search row">
      <div class="col-3">
        <input type="search" name="title" required placeholder="Find on TMDB" class="form-control">
      </div>
      <div class="col-1">
        <button class="btn btn-outline-secondary">Search</button>
      </div>
    </div>
  </form>
</div>

<% if !@tmdb_results.nil? %>
<p class="search-number">Found <%= pluralize @tmdb_results.count, "movie" %>.</p>
<div class="container">
   <div id="movie-search-results" class="row">
      <% @tmdb_results.uniq.each do |movie| %>
      <div class="card">
        <%= image_tag "https://image.tmdb.org/t/p/w600_and_h900_bestv2" + movie['poster_path'], :class => 'thumb-result', :alt => movie['title'] if movie['poster_path'].present? %>
        <div class="card-body">
          <p>
            <% if @current_user.present? %>
              <%= link_to add_movie_path(movie["id"]), :class => "btn btn-outline-info" do %>
                <i class="fas fa-plus"></i>
              <% end %>
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
    </div>
    <% else %>
  <p>No movies were found.</p>
  <% end %>
</div>