config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :users
  resources :movies
  resources :directors
  resources :lists
  resources :genres
  resources :actors

  # search and result from the TMDB using API
  get '/tmdb_result'=> 'pages#tmdb_result', :as => 'tmdb_result'
  get '/movies/add/:id' => 'movies#add', :as => 'add_movie'

  # session routes
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # search and result routes
  get '/show' => 'pages#search', :as => 'search'
  get '/result' => 'pages#result', :as => 'result'

  # route to user's lists
  get '/my_lists' => 'pages#my_lists', :as => 'my_lists'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moovi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">

  </head>

  <body>
    <div id="message">
    </div>
    
    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="/">Moovi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item"><%= link_to "Home", root_path, :class => "nav-link" %></li>
            <li class="nav-item"><%= link_to 'Movies', movies_path, :class => "nav-link" %></li>
            <li class="nav-item"><%= link_to "Genres", genres_path, :class => "nav-link" %></li>
            <li class="nav-item"><%= link_to "Actors", actors_path, :class => "nav-link" %></li>
            <li class="nav-item"><%= link_to "Directors", directors_path, :class => "nav-link" %></li>
            <li class="nav-item"><%= link_to "Lists", lists_path, :class => "nav-link" %></li>
            <% if @current_user.present? %>
              <% if @current_user.admin? %>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Administration
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <%= link_to "All Users", users_path, :class => "dropdown-item" %>
                    <%= link_to "Add Movie", new_movie_path, :class => "dropdown-item" %>
                    <%= link_to "Add Actor", new_actor_path, :class => "dropdown-item" %>
                    <%= link_to "Add Director", new_director_path, :class => "dropdown-item" %>
                    <%= link_to "Add Genre", new_genre_path, :class => "dropdown-item" %>
                  </div>
                </li>
              <% end %>
                <li class="nav-item"><%= link_to "New list", new_list_path, :class=> "nav-link" %></li>
                <li class="nav-item"><%= link_to "My lists", my_lists_path, :class => "nav-link" %></li>
                <li class="nav-item"><%= link_to "Log out", login_path, :method => 'delete', :class => "nav-link" %></li>
              <% else %>
                <li class="nav-item"><%= link_to "Sign Up", new_user_path, :class => "nav-link" %></li>
                <li class="nav-item"><%= link_to "Log In", login_path, :class => "nav-link" %></li>
            <% end %>
          </ul>

          <%= form_tag result_path, :method => "get", :class => "row" do %>
          <div class="col-8 search-query-box">
            <%= text_field_tag :search_query, nil, :class => "form-control mr-sm-2 query-box", :placeholder => "Find", :required => true %>
          </div>
          <div class="col-4 search-button">
            <%= button_tag :type => "submit", :class => "btn btn-outline-secondary", :name => nil do %>
              <i class="fas fa-search"></i>
            <% end %>
          </div>
          <% end %>
        </div>
      </nav>
    </header>

    <div class="wrapper">
      <div class="main-wrapper">
        <%= yield %>
      </div>
    </div>

  </body>
</html>